### ISSUE TITLE
problem running the make command

### ISSUE THREAD

**Issue by chmedly** [essandess/etv-comskip#67]
I get this line at the very bottom:
~/etv-comskip/etv-comskip/src/scripts/MarkCommercials ~/etv-comskip/etv-comskip
/bin/sh: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/pyinstaller: No such file or directory
make: *** [MarkCommercials] Error 127

I went through the list of sudo commands to get python27 working and the only one that didn't work was when I tried to uninstall inactive.  I got this error:  Error: No ports matched the given expression

btw, ultimately I'm hoping to run this version of comskip in KMTTG.  I get comskip failures about 50% of the time with the old old version of comskip that comes in KMTTG & I've had trouble getting a newer version running correctly in wine.

**Comment by chris299** [comment]
I had the same issue, because the macport install of 'pip' doesn't put it into the search path so 'sudo -H pip install pyinstaller' from make file fails.
@essandess you may want to change the command within the make file to 'sudo -H  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/pip install pyinstaller' :)
