### ISSUE TITLE
improvement suggestions for makefile

### ISSUE THREAD

**Issue by chris299** [essandess/etv-comskip#69]
First, I want to thank you for the great work done here!!

However, I had some issues making etv-comskip work for me, so I wanted to share them with you:
- make only worked as sudoer for me due to permission issues
- it may be worth to mention, that make will put the installer script do the download directory (in the readme)
- starting pip failed without the path, see also #67 
- 'pip install objc' fails with error:  "Collecting objc:  Could not find a version that satisfies the requirement objc (from versions: ) No matching distribution found for objc"
however, it works without it, so you may want to remove this from makefile
- I had some issues to to setup the buid environment as the echo statements don't match the makefile commands regarding X11 support. I finally put it togehter by hand without X11 and it seems to work.
However, it may be a problem for comskip-gui but I didn't really test that.
- starting comskip-gui gives a message 'objc[22787]: Class SDLTranslatorResponder is implemented in both /Users/chris299/Downloads/ETVComskip/lib/libSDL2-2.0.0.dylib and /Users/chris299/Downloads/ETVComskip/lib/libSDL-1.2.0.dylib. One of the two will be used. Which one is undefined.'
It may be worth checking and removing one of the libraries

I hope this helps and I would be more than happy to answer additional questions regarding my setup.

kind regards
Christoph

**Comment by essandess** [comment]
Thank you for the detailed comments. I just upgraded to 10.13, and have it on my to do list tp recompile for High Sierra—I’ll do my best to incorporate these improvements.

**Comment by chris299** [comment]
@essandess  Thank you.
unfortunately I forgot one more:
- as make exits with error if the directories ./bin (local path of repository) or .../Download/etv-comskip are already there (i.e. from previous failed makes ;-), it may make sense to remove both on existence when starting a new make run.

**Comment by essandess** [comment]
Checking these off:

- make only worked as sudoer for me due to permission issues

`sudo` is necessary to install several development tools

- it may be worth to mention, that make will put the installer script do the download directory (in the readme)

Done.

- starting pip failed without the path, see also #67 

That looks like a PATH issue. I explicitly created a PIP with full path to version 2.7 to address.

- 'pip install objc' fails with error:  "Collecting objc:  Could not find a version that satisfies the requirement objc (from versions: ) No matching distribution found for objc"
however, it works without it, so you may want to remove this from makefile

The makefile should go ahead without that—that's what the `-[[…]]` Makefile directive is for. I can't recall why this dependency was included, just that I needed at some point. I'm going to keep until I hear more feedback or run into this issue myself.

- I had some issues to to setup the buid environment as the echo statements don't match the makefile commands regarding X11 support. I finally put it togehter by hand without X11 and it seems to work.
However, it may be a problem for comskip-gui but I didn't really test that.

?? There are no specific X11 Makefile commands.

- starting comskip-gui gives a message 'objc[22787]: Class SDLTranslatorResponder is implemented in both /Users/chris299/Downloads/ETVComskip/lib/libSDL2-2.0.0.dylib and /Users/chris299/Downloads/ETVComskip/lib/libSDL-1.2.0.dylib. One of the two will be used. Which one is undefined.'
It may be worth checking and removing one of the libraries

That's a (perhaps isolated) of combining all the dynamic libraries in one `./lib` location. I'm do not plan to address this.

- as make exits with error if the directories ./bin (local path of repository) or .../Download/etv-comskip are already there (i.e. from previous failed makes ;-), it may make sense to remove both on existence when starting a new make run.

Done.
